# last_verified: 2026-08-19 · Kubernetes n/a
apiVersion: v1
kind: Secret
metadata:
  name: sample-app-secrets
  namespace: sample-app
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQxMjM=
  API_KEY: ZGVmYXVsdC1hcGkta2V5
